import React, { useState, useEffect } from 'react';
import { X, Calendar, MapPin, Copy, Check, ExternalLink, Mail, AlertTriangle, UserCheck, UserX, FlaskConical } from 'lucide-react';
import { TeamMember, MeetingConfig } from '../types';
import { getHourInZone, isWorkHour, formatTimeInZone } from '../utils/timeUtils';
import { getHolidayForDate } from '../utils/holidayUtils';
import { createGoogleCalendarEvent, sendGmail } from '../utils/googleApi';
import { generateInviteText } from '../utils/calendarUtils';

interface ScheduleMeetingModalProps {
  isOpen: boolean;
  onClose: () => void;
  selectedDate: Date;
  members: TeamMember[];
  onToast: (msg: string, type: 'success' | 'error' | 'info') => void;
  onSchedule: (config: MeetingConfig, date: Date, participants: string[]) => void;
  isDemo?: boolean;
}

export const ScheduleMeetingModal: React.FC<ScheduleMeetingModalProps> = ({ 
  isOpen, 
  onClose, 
  selectedDate, 
  members,
  onToast,
  onSchedule,
  isDemo = false
}) => {
  const [config, setConfig] = useState<MeetingConfig>({
    title: 'Team Sync',
    duration: 30,
    description: 'Weekly coordination meeting to discuss progress and blockers.',
    location: 'Google Meet',
  });
  
  const [selectedMemberIds, setSelectedMemberIds] = useState<Set<string>>(new Set());
  const [isPast, setIsPast] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [sendConfirmationEmail, setSendConfirmationEmail] = useState(false);

  useEffect(() => {
    if (isOpen) {
        // Validate if selected date is in the past (allow 5 min buffer)
        const now = new Date();
        const diff = selectedDate.getTime() - now.getTime();
        // If diff is less than -5 minutes, it's past
        setIsPast(diff < -5 * 60 * 1000);

        setSelectedMemberIds(new Set(members.map(m => m.id)));
    }
  }, [isOpen, members, selectedDate]);

  if (!isOpen) return null;

  const toggleMember = (id: string) => {
    const newSet = new Set(selectedMemberIds);
    if (newSet.has(id)) {
        newSet.delete(id);
    } else {
        newSet.add(id);
    }
    setSelectedMemberIds(newSet);
  };

  const toggleAll = () => {
    if (selectedMemberIds.size === members.length) {
        setSelectedMemberIds(new Set());
    } else {
        setSelectedMemberIds(new Set(members.map(m => m.id)));
    }
  };

  const activeMembers = members.filter(m => selectedMemberIds.has(m.id));

  const handleSyncAndSend = async () => {
    if (activeMembers.length === 0) {
        onToast('Please select at least one participant', 'error');
        return;
    }

    setIsSending(true);

    try {
        const endTime = new Date(selectedDate.getTime() + config.duration * 60000);
        
        // 1. Internal State Update
        onSchedule(config, selectedDate, activeMembers.map(m => m.name));

        if (isDemo) {
            // SIMULATION MODE
            await new Promise(resolve => setTimeout(resolve, 1500)); // Fake network delay
            onToast('Demo Mode: Calendar Event & Email Simulated!', 'success');
            onClose();
            setIsSending(false);
            return;
        }

        // 2. Real Google Calendar Create (Auto-sends invites via 'sendUpdates': 'all')
        const attendees = activeMembers
            .map(m => m.email?.trim())
            .filter((email): email is string => Boolean(email));

        if (attendees.length === 0) {
            onToast('No participant emails found. Add emails to team members to send calendar invites.', 'error');
            return;
        }

        if (attendees.length < activeMembers.length) {
            onToast('Some members have no email; invites will be sent only to members with email.', 'info');
        }

        await createGoogleCalendarEvent({
            title: config.title,
            description: config.description,
            location: config.location,
            start: selectedDate,
            end: endTime
        }, attendees);
        
        let successMsg = 'Google Calendar Event Created!';

        // 3. Optional: Send detailed email via Gmail API
        if (sendConfirmationEmail) {
            const body = `
                <h2>Meeting Invitation: ${config.title}</h2>
                <p><strong>Time:</strong> ${selectedDate.toLocaleString()}</p>
                <p><strong>Duration:</strong> ${config.duration} minutes</p>
                <p><strong>Location:</strong> ${config.location}</p>
                <p><strong>Description:</strong><br/>${config.description}</p>
                <hr/>
                <p>Generated by ChronosSync</p>
            `;
            await sendGmail(attendees, `INVITE: ${config.title}`, body);
            successMsg += ' & Confirmation Email Sent';
        }

        onToast(successMsg, 'success');
        onClose();

    } catch (error) {
        console.error("Failed to schedule", error);
        onToast('Failed to create event. Is Google Login active?', 'error');
    } finally {
        setIsSending(false);
    }
  };

  // Analyze availability
  const analysis = members.map(m => {
    const isSelected = selectedMemberIds.has(m.id);
    const localHour = getHourInZone(selectedDate, m.timezone);
    const holiday = getHolidayForDate(selectedDate, m.timezone);
    const isWorking = isWorkHour(localHour, m.workStart, m.workEnd);
    const isSleep = localHour >= 23 || localHour < 7;
    
    let status: 'ok' | 'warning' | 'bad' = 'ok';
    let message = 'Available';

    if (holiday) {
        status = 'bad';
        message = `Holiday: ${holiday}`;
    } else if (isSleep) {
        status = 'bad';
        message = 'Likely Sleeping';
    } else if (!isWorking) {
        status = 'warning';
        message = 'Outside Work Hours';
    }

    return { member: m, status, message, localTime: formatTimeInZone(selectedDate, m.timezone), isSelected };
  });

  const activeAnalysis = analysis.filter(a => a.isSelected);
  const issueCount = activeAnalysis.filter(a => a.status !== 'ok').length;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-text-main/60 backdrop-blur-sm animate-fade-in">
      <div className="bg-surface border border-stroke rounded-lg w-full max-w-2xl shadow-2xl animate-slide-up flex flex-col max-h-[90vh]">
        
        {/* Header */}
        <div className="flex justify-between items-center p-6 border-b border-stroke bg-canvas">
          <div>
            <h2 className="text-xl font-bold text-text-main flex items-center gap-2">
              <Calendar className="h-5 w-5 text-brand-500" />
              Schedule Meeting
              {isDemo && <span className="text-xs bg-amber-100 text-amber-800 px-2 py-0.5 rounded-full flex items-center gap-1"><FlaskConical className="w-3 h-3"/> Demo Mode</span>}
            </h2>
            <p className="text-sm text-text-sub mt-1">
                {selectedDate.toLocaleDateString(undefined, {weekday: 'long', month: 'long', day: 'numeric'})} at {selectedDate.toLocaleTimeString(undefined, {hour: 'numeric', minute:'2-digit'})}
            </p>
          </div>
          <button onClick={onClose} aria-label="Close modal" className="text-text-sub hover:text-text-main transition-colors p-2 hover:bg-stroke rounded-full">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-6">
             {isPast && (
                <div className="mb-6 bg-red-50 border border-red-200 rounded p-3 flex items-start gap-3 text-red-800">
                    <AlertTriangle className="w-5 h-5 shrink-0 mt-0.5" />
                    <div className="text-sm">
                        <span className="font-bold block">Invalid Time Selection</span>
                        You cannot schedule a meeting in the past. Please select a future time slot on the timeline.
                    </div>
                </div>
            )}

            <div className={`grid grid-cols-1 md:grid-cols-2 gap-8 ${isPast ? 'opacity-50 pointer-events-none' : ''}`}>
                {/* Configuration Form */}
                <div className="space-y-5">
                    <div>
                        <label className="block text-xs font-bold text-text-sub mb-1.5 uppercase tracking-wide">Event Title</label>
                        <input 
                            type="text" 
                            className="w-full bg-surface border border-stroke rounded-[3px] px-3 py-2 text-text-main focus:ring-2 focus:ring-brand-100 focus:border-brand-400 outline-none text-sm font-medium"
                            value={config.title}
                            onChange={e => setConfig({...config, title: e.target.value})}
                        />
                    </div>

                    <div>
                        <label className="block text-xs font-bold text-text-sub mb-1.5 uppercase tracking-wide">Duration</label>
                        <div className="flex gap-2">
                            {[15, 30, 45, 60].map(mins => (
                                <button
                                    key={mins}
                                    onClick={() => setConfig({...config, duration: mins})}
                                    className={`flex-1 py-2 text-xs font-medium rounded-[3px] border transition-all ${
                                        config.duration === mins 
                                        ? 'bg-brand-50 border-brand-300 text-brand-600' 
                                        : 'bg-surface border-stroke text-text-sub hover:bg-canvas'
                                    }`}
                                >
                                    {mins}m
                                </button>
                            ))}
                        </div>
                    </div>

                    <div>
                        <label className="block text-xs font-bold text-text-sub mb-1.5 uppercase tracking-wide">Location / Link</label>
                        <div className="relative">
                            <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-text-muted" />
                            <input 
                                type="text" 
                                className="w-full bg-surface border border-stroke rounded-[3px] pl-9 pr-3 py-2 text-text-main focus:ring-2 focus:ring-brand-100 focus:border-brand-400 outline-none text-sm"
                                value={config.location}
                                onChange={e => setConfig({...config, location: e.target.value})}
                            />
                        </div>
                    </div>

                    <div>
                        <label className="block text-xs font-bold text-text-sub mb-1.5 uppercase tracking-wide">Description</label>
                        <textarea 
                            rows={3}
                            className="w-full bg-surface border border-stroke rounded-[3px] px-3 py-2 text-text-main focus:ring-2 focus:ring-brand-100 focus:border-brand-400 outline-none text-sm resize-none"
                            value={config.description}
                            onChange={e => setConfig({...config, description: e.target.value})}
                        />
                    </div>
                    
                    <div className="flex items-start gap-2 pt-2">
                        <input 
                            type="checkbox" 
                            id="sendEmail" 
                            className="mt-0.5 rounded border-stroke text-brand-600 focus:ring-brand-500"
                            checked={sendConfirmationEmail}
                            onChange={e => setSendConfirmationEmail(e.target.checked)}
                        />
                        <label htmlFor="sendEmail" className="text-sm text-text-main leading-tight cursor-pointer">
                            Send separate email via Gmail
                            <span className="block text-xs text-text-muted mt-0.5">Sends a formatted email in addition to the calendar invite.</span>
                        </label>
                    </div>
                </div>

                {/* Participant Check */}
                <div className="bg-canvas/50 rounded-lg border border-stroke p-4 flex flex-col h-full">
                    <div className="flex items-center justify-between mb-3">
                        <h3 className="text-sm font-bold text-text-main flex items-center gap-2">
                            Participants
                            {issueCount > 0 && (
                                <span className="text-[10px] bg-yellow-100 text-yellow-800 px-2 py-0.5 rounded-full font-bold">
                                    {issueCount} Issues
                                </span>
                            )}
                        </h3>
                        <button 
                            onClick={toggleAll}
                            className="text-[10px] font-bold text-brand-600 hover:text-brand-700 uppercase tracking-wide hover:bg-brand-50 px-2 py-1 rounded"
                        >
                            {selectedMemberIds.size === members.length ? 'None' : 'All'}
                        </button>
                    </div>
                    
                    <div className="flex-1 overflow-y-auto space-y-2 pr-1 custom-scrollbar">
                        {analysis.map((item, idx) => (
                            <div 
                                key={idx} 
                                onClick={() => toggleMember(item.member.id)}
                                className={`flex items-center justify-between p-2 rounded-[3px] border cursor-pointer transition-all ${
                                    item.isSelected 
                                    ? 'bg-surface border-stroke shadow-sm' 
                                    : 'bg-canvas-subtle/50 border-transparent opacity-60 hover:opacity-100'
                                }`}
                            >
                                <div className="flex items-center gap-3">
                                    <div className={`w-4 h-4 rounded border flex items-center justify-center transition-colors ${
                                        item.isSelected ? 'bg-brand-500 border-brand-500' : 'bg-white border-stroke'
                                    }`}>
                                        {item.isSelected && <Check className="w-3 h-3 text-white" />}
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <div className={`w-2 h-2 rounded-full ${
                                            !item.isSelected ? 'bg-gray-300' :
                                            item.status === 'ok' ? 'bg-green-500' : 
                                            item.status === 'warning' ? 'bg-yellow-500' : 'bg-red-500'
                                        }`} />
                                        <span className={`font-medium text-sm ${item.isSelected ? 'text-text-main' : 'text-text-muted'}`}>
                                            {item.member.name}
                                        </span>
                                    </div>
                                </div>
                                <div className="text-right">
                                    <div className={`text-xs font-bold ${item.isSelected ? 'text-text-main' : 'text-text-muted'}`}>
                                        {item.localTime}
                                    </div>
                                    {item.isSelected && item.status !== 'ok' && (
                                        <div className={`text-[10px] flex items-center justify-end gap-1 ${
                                             item.status === 'warning' ? 'text-yellow-600' : 'text-red-600'
                                        }`}>
                                            {item.status === 'bad' && <AlertTriangle className="w-3 h-3" />}
                                            {item.message}
                                        </div>
                                    )}
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
        </div>

        {/* Footer Actions */}
        <div className="p-6 border-t border-stroke bg-canvas flex justify-between items-center gap-4">
             <div className="text-xs text-text-muted font-medium flex items-center gap-1.5">
                {isPast ? (
                     <span className="text-red-600 font-bold">Cannot schedule in the past</span>
                ) : activeMembers.length === 0 ? (
                    <span className="text-red-600 flex items-center gap-1"><UserX className="w-3 h-3"/> No participants selected</span>
                ) : (
                    <span className="text-brand-600 flex items-center gap-1"><UserCheck className="w-3 h-3"/> {activeMembers.length} participants selected</span>
                )}
             </div>
             <div className="flex gap-3">
                <button 
                    onClick={handleSyncAndSend}
                    disabled={activeMembers.length === 0 || isPast || isSending}
                    className="flex items-center gap-2 px-6 py-2.5 rounded-[3px] bg-brand-600 hover:bg-brand-500 text-white shadow-md transition-all text-sm font-bold active:translate-y-0.5 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                    {isSending ? (
                        <>
                         <div className="animate-spin rounded-full h-4 w-4 border-2 border-white border-t-transparent"></div>
                         Sending...
                        </>
                    ) : (
                        <>
                        <Mail className="w-4 h-4" />
                        {isDemo ? 'Send Fake Invite' : 'Send Invites'}
                        </>
                    )}
                </button>
             </div>
        </div>
      </div>
    </div>
  );
};