import { TeamMember } from '../types';
import { formatTimeInZone } from './timeUtils';

export const generateICSFile = (
  title: string,
  description: string,
  location: string,
  startTime: Date,
  durationMinutes: number
): string => {
  const endTime = new Date(startTime.getTime() + durationMinutes * 60000);

  const formatDate = (date: Date): string => {
    return date.toISOString().replace(/[-:]/g, '').split('.')[0] + 'Z';
  };

  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//ChronosSync//Team Coordinator//EN',
    'BEGIN:VEVENT',
    `UID:${Date.now()}@chronossync.app`,
    `DTSTAMP:${formatDate(new Date())}`,
    `DTSTART:${formatDate(startTime)}`,
    `DTEND:${formatDate(endTime)}`,
    `SUMMARY:${title}`,
    `DESCRIPTION:${description}`,
    `LOCATION:${location}`,
    'END:VEVENT',
    'END:VCALENDAR'
  ].join('\r\n');

  return icsContent;
};

export const downloadICS = (content: string, filename: string) => {
  const blob = new Blob([content], { type: 'text/calendar;charset=utf-8' });
  const link = document.createElement('a');
  link.href = window.URL.createObjectURL(blob);
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const generateInviteText = (
  title: string,
  location: string,
  startTime: Date,
  duration: number,
  members: TeamMember[]
): string => {
  const header = `📅 Invitation: ${title}\n⏳ Duration: ${duration} mins\n📍 Location: ${location}\n\nTime across zones:\n`;
  
  // Group members by timezone to avoid duplicates
  const zoneGroups: Record<string, string[]> = {};
  
  members.forEach(m => {
    if (!zoneGroups[m.timezone]) {
      zoneGroups[m.timezone] = [];
    }
    zoneGroups[m.timezone].push(m.name);
  });

  const times = Object.keys(zoneGroups).map(tz => {
    const timeStr = formatTimeInZone(startTime, tz, 'h:mm a');
    const dateStr = new Intl.DateTimeFormat('en-US', { timeZone: tz, weekday: 'short', month: 'short', day: 'numeric' }).format(startTime);
    const people = zoneGroups[tz].join(', ');
    return `• ${timeStr} (${dateStr}) - ${tz.split('/')[1].replace('_', ' ')}\n  For: ${people}`;
  }).join('\n');

  return `${header}${times}\n\nGenerated by ChronosSync`;
};